import Icon from "./OperationsIcon";
import { ContextCard, DataBar, SectionHeading, StatusDistribution } from "./OperationsVisuals";
import { dateLabel, numberLabel } from "../services/operationsApi";
import { moneyLabel, totalMoney } from "../services/siteApi";
import "../styles/ModulePolish.css";

export function AssignmentOverview({ tasks, teams, onSelect }) {
  const attention = tasks.filter((task)=>task.is_late || task.open_issues > 0);
  return <div className="assignment-overview"><section className="ops-card"><SectionHeading icon="users" title="Phân bổ công việc" description={`${tasks.length} công việc · ${teams.length} đội thi công`} /><div className="assignment-workload">{teams.map((team)=><DataBar key={team.id} label={team.name} value={tasks.filter((task)=>task.team_id===team.id).length} max={tasks.length} display={`${tasks.filter((task)=>task.team_id===team.id).length} công việc`} note={`${team.members.length} thành viên`} />)}<DataBar label="Chưa phân công" value={tasks.filter((task)=>!task.team_id).length} max={tasks.length} color="orange" display={`${tasks.filter((task)=>!task.team_id).length} công việc`} /></div></section><section className="ops-card"><SectionHeading icon="warning" tone="orange" title="Cần theo dõi" description={`${tasks.filter((task)=>task.isCritical).length} công việc găng · ${attention.length} công việc có cảnh báo`} /><div className="assignment-attention">{attention.length ? attention.slice(0,4).map((task)=><button key={task.id} onClick={()=>onSelect(task)}><span><strong>{task.name}</strong><small>{task.team_name || "Chưa phân công"}</small></span><span className="ops-badge ops-badge-orange">{task.open_issues > 0 ? `${task.open_issues} vướng mắc` : "Trễ tiến độ"}</span><Icon name="right" size={15}/></button>) : <ContextCard icon="check" tone="green" title="Không có cảnh báo đang mở">Theo tiến độ và vướng mắc hiện tại của các công việc trong danh sách.</ContextCard>}</div></section></div>;
}

export function JournalOverview({ journals, queue, offline }) {
  const photos = queue.reduce((sum, entry)=>sum+entry.photos.filter((photo)=>!photo.photoId).length,0);
  return <div className="journal-overview"><div className="journal-book"><span className="visual-icon"><Icon name="document" size={25}/></span><div><span>SỔ NHẬT KÝ CÔNG TRƯỜNG</span><h2>{journals.length} bản ghi đã đồng bộ</h2><p>{new Set(journals.map((entry)=>entry.day)).size} ngày ghi nhận · {new Set(journals.filter((entry)=>entry.locked).map((entry)=>entry.day)).size} ngày đã khóa sổ</p></div></div><div className={`journal-sync ${offline ? "is-offline" : ""}`}><span className="ops-badge">{offline ? "Đang ngoại tuyến" : "Đã kết nối"}</span><strong>{queue.length} bản ghi chờ đồng bộ</strong><small>{photos} ảnh đang lưu trên thiết bị</small></div></div>;
}

export function ContractProgress({ contracts }) {
  return <aside className="ops-card contract-progress"><SectionHeading icon="check" tone="green" title="Khối lượng đã nghiệm thu" description={`${contracts.length} hạng mục đã khai báo hợp đồng`} />{contracts.length ? contracts.map((contract)=><DataBar key={contract.work_item_id} label={contract.item_name} value={Number(contract.approved_quantity)} max={Number(contract.quantity)} color="green" display={`${numberLabel(contract.approved_quantity)} / ${numberLabel(contract.quantity)} ${contract.unit}`} note="Lũy kế từ phiếu đã duyệt" />) : <p className="ops-muted">Khai báo hợp đồng để theo dõi khối lượng nghiệm thu.</p>}<ContextCard icon="document" title="Cơ sở lập thanh toán">Phiếu được duyệt sẽ cập nhật lũy kế và có thể dùng để lập đề nghị thanh toán.</ContextCard></aside>;
}

export function PaymentOverview({ approved }) {
  const gross = totalMoney(approved,"gross"), net = totalMoney(approved,"net"), retained = totalMoney(approved,"retained");
  const ratio = Number(gross) > 0 ? Number(net) / Number(gross) * 100 : 0;
  return <div className="payment-overview"><section className="finance-hero"><span className="finance-eyebrow"><Icon name="money" size={18}/> GIÁ TRỊ HỒ SƠ ĐÃ DUYỆT</span><span className="finance-label">Giá trị thực trả</span><strong>{moneyLabel(net)} <small>₫</small></strong><p>{approved.length} đề nghị đã phê duyệt · Theo số liệu hồ sơ</p></section><section className="ops-card finance-breakdown"><SectionHeading icon="chart" title="Cơ cấu thanh toán" description="Tổng giá trị đã duyệt và phần tạm giữ" /><div className="finance-split" aria-hidden="true"><span style={{width:`${Math.min(100,Math.max(0,ratio))}%`}}/></div><dl><div><dt><i/>Thực trả</dt><dd>{moneyLabel(net)} ₫</dd></div><div><dt><i/>Tạm giữ</dt><dd>{moneyLabel(retained)} ₫</dd></div><div><dt>Tổng thành tiền</dt><dd>{moneyLabel(gross)} ₫</dd></div></dl></section></div>;
}

export function CostOverview({ data, rootRows }) {
  const budget = totalMoney(rootRows,"budget");
  return <div className="cost-overview"><section className="ops-card cost-totals"><SectionHeading icon="money" title="Ngân sách & chi phí" description="Tổng hợp theo danh mục hạng mục dự án" /><div><span>Dự toán hiện tại</span><strong>{moneyLabel(budget)} <small>₫</small></strong></div><div><span>Tổng thực chi</span><strong className="cost-actual">{moneyLabel(totalMoney(data.costs,"amount"))} <small>₫</small></strong></div><footer><span>{data.costs.filter((cost)=>!cost.work_item_id).length} khoản chờ phân bổ</span><span>{data.materials.length} loại vật tư</span></footer></section><section className="ops-card cost-bars"><SectionHeading icon="chart" title="Mức sử dụng dự toán" description="Thực chi / dự toán của hạng mục gốc" />{rootRows.length ? rootRows.map((row)=><DataBar key={row.id} label={row.title} value={row.usage_percent} color={row.warning ? "orange" : "blue"} display={row.usage_percent == null ? "Chưa có dự toán" : `${row.usage_percent.toFixed(1)}%`} note={`${moneyLabel(row.actual)} / ${moneyLabel(row.budget)} ₫`} />) : <p className="ops-muted">Chưa có hạng mục để đối chiếu chi phí.</p>}</section></div>;
}

export function PhotoOverview({ photos, onReview }) {
  return <div className="photo-overview"><div><span className="visual-icon"><Icon name="photo" size={26}/></span><div><strong>{photos.length} ảnh hiện trường</strong><small>{new Set(photos.map((photo)=>photo.work_item_id)).size} hạng mục có ảnh · {new Set(photos.map((photo)=>photo.uploaded_by)).size} người đóng góp</small></div></div><div className="photo-overview-counts"><span><strong>{photos.filter((photo)=>photo.metadata.has_exif).length}</strong>Có metadata EXIF</span><button onClick={onReview}><strong>{photos.filter((photo)=>photo.suspicious).length}</strong>Ảnh cần kiểm tra <Icon name="right" size={13}/></button></div></div>;
}

export function ReportOverview({ data }) {
  const completed = data.tasks.filter((task)=>task.complete).length;
  return <div className="report-overview"><section className="report-progress-hero"><span className="finance-eyebrow"><Icon name="trend" size={18}/> TIẾN ĐỘ THI CÔNG</span><strong>{data.progress == null ? "—" : `${data.progress.toFixed(1)}%`}</strong><p>{data.progress == null ? "Chưa đủ dữ liệu khối lượng để tính tiến độ tổng thể." : "Tổng hợp theo khối lượng thực hiện của công việc."}</p><div className="visual-track"><span style={{width:`${Math.max(0,Math.min(100,data.progress || 0))}%`}}/></div><footer><span>Kết thúc kế hoạch</span><b>{dateLabel(data.planned_finish)}</b></footer></section><section className="ops-card"><StatusDistribution title="Tình trạng công việc" label="Công việc" entries={[{label:"Hoàn thành",value:completed,color:"#17b26a"},{label:"Chưa hoàn thành",value:data.tasks.length-completed,color:"#d3dfef"}]} /><p className="report-distribution-note">{data.tasks.filter((task)=>task.isCritical && task.is_late).length} công việc găng đang trễ · {data.milestones.filter((milestone)=>milestone.overdue).length} mốc quá hạn</p></section><section className="ops-card report-finance"><SectionHeading icon="money" tone="orange" title="Tài chính dự án" description="Theo số liệu đã ghi nhận" /><span>Tổng thực chi</span><strong>{moneyLabel(totalMoney(data.costs,"amount"))} <small>₫</small></strong><div><Icon name="check" size={16}/>{data.acceptances.filter((form)=>form.status==="approved").length} phiếu nghiệm thu đã duyệt</div></section></div>;
}
