const express = require("express");
const { requireAuth } = require("../middleware/auth");
const { createProjectAccess } = require("../middleware/projectAccess");
const { createProjectMemberModel } = require("../models/projectMemberModel");
const { createProjectOperationsModel } = require("../models/projectOperationsModel");
const { createProjectOperationsService } = require("../services/projectOperationsService");
const { createProjectOperationsController } = require("../controllers/projectOperationsController");
const READ = ["admin", "project_manager", "engineer", "worker", "accountant", "viewer", "manager", "member"];
const MANAGE = ["admin", "project_manager", "manager"];
function createProjectOperationsRoutes({ pool, authorization = { requireAuth } } = {}) {
    pool ||= require("../config/database");
    const router = express.Router();
    const access = createProjectAccess({ memberModel: createProjectMemberModel(pool) });
    const controller = createProjectOperationsController({ service: createProjectOperationsService({ model: createProjectOperationsModel(pool) }) });
    router.use(authorization.requireAuth);
    router.get("/", controller.listProjects);
    router.post("/", controller.createProject);
    const route = (method, path, roles, handler) => router[method](path, access.requireProjectMember(...roles), handler);
    route("get", "/:projectId/overview", READ, controller.project);
    route("patch", "/:projectId/overview", MANAGE, controller.updateProject);
    route("get", "/:projectId/calendar", READ, controller.calendar);
    route("put", "/:projectId/calendar", MANAGE, controller.saveCalendar);
    route("post", "/:projectId/holidays", MANAGE, controller.saveHoliday);
    route("put", "/:projectId/holidays/:holidayId", MANAGE, controller.saveHoliday);
    route("delete", "/:projectId/holidays/:holidayId", MANAGE, controller.deleteHoliday);
    route("get", "/:projectId/participants", MANAGE, controller.participants);
    route("get", "/:projectId/members", READ, controller.members);
    route("post", "/:projectId/members", MANAGE, controller.inviteMember);
    route("patch", "/:projectId/members/:userId", MANAGE, controller.changeMemberRole);
    route("delete", "/:projectId/members/:userId", MANAGE, controller.removeMember);
    route("delete", "/:projectId/invitations/:invitationId", MANAGE, controller.cancelInvitation);
    route("get", "/:projectId/teams", READ, controller.teams);
    route("post", "/:projectId/teams", MANAGE, controller.createTeam);
    route("get", "/:projectId/assignments", [...MANAGE, "worker", "engineer", "viewer"], controller.assignments);
    route("put", "/:projectId/assignments/:taskId", MANAGE, controller.assign);
    route("get", "/:projectId/assignments/:taskId", [...MANAGE, "worker", "engineer", "viewer"], controller.details);
    route("put", "/:projectId/assignments/:taskId/quantity", MANAGE, controller.saveQuantity);
    route("post", "/:projectId/assignments/:taskId/progress", ["worker"], controller.reportProgress);
    route("post", "/:projectId/assignments/:taskId/issues", ["worker"], controller.reportIssue);
    route("patch", "/:projectId/issues/:issueId/close", MANAGE, controller.closeIssue);
    route("get", "/:projectId/notifications", READ, controller.notifications);
    route("patch", "/:projectId/notifications/read-all", READ, controller.readNotifications);
    route("patch", "/:projectId/notifications/:notificationId/read", READ, controller.readNotifications);
    route("get", "/:projectId/audit-logs", MANAGE, controller.auditLogs);
    return router;
}
module.exports = { createProjectOperationsRoutes };
