const express = require("express");
const { requireAuth } = require("../middleware/auth");
const { createProjectAccess } = require("../middleware/projectAccess");
const { createProjectMemberModel } = require("../models/projectMemberModel");
const { createSiteManagementModel } = require("../models/siteManagementModel");
const { createSiteManagementService } = require("../services/siteManagementService");
const { createReportPdfService } = require("../services/reportPdfService");
const { createSiteManagementController } = require("../controllers/siteManagementController");
const MANAGE=["admin","project_manager","manager"];
const READ=[...MANAGE,"engineer","viewer","accountant"];
const FIELD=[...MANAGE,"engineer"];
const FINANCE=[...MANAGE,"accountant","viewer"];
const EDIT_COST=[...MANAGE,"accountant"];
function createSiteManagementRoutes({ pool,authorization={ requireAuth } } = {}) {
    pool ||= require("../config/database");
    const model=createSiteManagementModel(pool);
    const controller=createSiteManagementController({ service:createSiteManagementService({ model }),pdfService:createReportPdfService({ model }) });
    const access=createProjectAccess({ memberModel:createProjectMemberModel(pool) });
    const router=express.Router(); router.use(authorization.requireAuth);
    const route=(method,path,roles,handler) => router[method](path,access.requireProjectMember(...roles),handler);
    route("get","/:projectId/lookup",[...READ,"worker"],controller.lookup);
    route("get","/:projectId/settings",[...READ,"worker"],controller.settings);
    route("put","/:projectId/settings",MANAGE,controller.saveSettings);
    route("put","/:projectId/preferences",[...READ,"worker"],controller.preferences);
    route("patch","/:projectId/account",[...READ,"worker"],controller.profile);
    route("get","/:projectId/photos",[...READ,"worker"],controller.photos);
    route("post","/:projectId/photos",[...FIELD,"worker"],controller.uploadPhoto);
    route("get","/:projectId/photos/:recordId/:variant",[...READ,"worker"],controller.photoFile);
    route("post","/:projectId/issues/:recordId/photos",["worker"],controller.issuePhotos);
    route("get","/:projectId/journals",READ,controller.journals);
    route("get","/:projectId/journals/daily",READ,controller.journalDaily);
    route("post","/:projectId/journals",FIELD,controller.saveJournal);
    route("post","/:projectId/journals/sync",FIELD,controller.syncJournals);
    route("put","/:projectId/journals/lock",FIELD,controller.lockJournal);
    route("post","/:projectId/journals/lock",FIELD,controller.lockJournal);
    route("post","/:projectId/journals/:recordId/lock",FIELD,controller.lockJournal);
    route("put","/:projectId/journals/:recordId",FIELD,controller.saveJournal);
    route("patch","/:projectId/journals/:recordId",FIELD,controller.saveJournal);
    route("delete","/:projectId/journals/:recordId",FIELD,controller.deleteJournal);
    route("get","/:projectId/acceptance",READ,controller.acceptance);
    route("put","/:projectId/contracts/:recordId",MANAGE,controller.contract);
    route("post","/:projectId/acceptance",FIELD,controller.saveAcceptance);
    route("put","/:projectId/acceptance/:recordId",FIELD,controller.saveAcceptance);
    route("post","/:projectId/acceptance/:recordId/transition",[...FIELD,"viewer"],controller.transitionAcceptance);
    route("get","/:projectId/payments",FINANCE,controller.payments);
    route("post","/:projectId/payments",["admin","accountant"],controller.savePayment);
    route("put","/:projectId/payments/:recordId",["admin","accountant"],controller.savePayment);
    route("post","/:projectId/payments/:recordId/transition",["admin","accountant","viewer"],controller.transitionPayment);
    route("get","/:projectId/costs",FINANCE,controller.costs);
    route("post","/:projectId/budgets",EDIT_COST,controller.budget);
    route("post","/:projectId/costs",EDIT_COST,controller.createCost);
    route("post","/:projectId/costs/import",EDIT_COST,controller.importCosts);
    route("patch","/:projectId/costs/:recordId/allocate",EDIT_COST,controller.allocateCost);
    route("post","/:projectId/materials",EDIT_COST,controller.material);
    route("post","/:projectId/inventory",EDIT_COST,controller.inventory);
    route("put","/:projectId/material-norms",EDIT_COST,controller.norm);
    route("get","/:projectId/reports",FINANCE,controller.report);
    route("post","/:projectId/milestones",MANAGE,controller.milestone);
    route("get","/:projectId/reports/acceptance.pdf",FINANCE,controller.reportPdf);
    return router;
}
module.exports = { createSiteManagementRoutes };
