import { expect,test } from "@playwright/test";
import process from "node:process";
import { Buffer } from "node:buffer";
import { readFile } from "node:fs/promises";

test.skip(!process.env.OPERATIONS_REAL_E2E,"Requires isolated PostgreSQL E2E server");
const photo={ name:"nhat-ky.jpg",mimeType:"image/jpeg",buffer:Buffer.from("/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAIAAgDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEBAAAAAAAAAAAAAAAAAAAABv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AIABqGv/2Q==","base64") };
async function login(page,role) { expect((await page.request.post("/auth/login",{ data:{ email:`${role}@e2e.test`,password:"Operations-only-E2E-123!" } })).status()).toBe(200); }
async function fixture(page) { return (await page.request.get("http://127.0.0.1:3031/__fixture")).json(); }
async function saveDialog(page,label="Lưu") { const dialog=page.getByRole("dialog"); await dialog.getByRole("button",{ name:label,exact:true }).click(); await expect(dialog).toHaveCount(0); }
async function transition(page,row,action) { await row.getByRole("button",{ name:action,exact:true }).click(); await saveDialog(page,action==="Duyệt" ? "Duyệt phiếu" : action); }

test("journal persists offline with photo across reload, syncs once, locks and unlocks with audit",async ({ page,context }) => {
  test.skip(!process.env.PWA_PRODUCTION_E2E,"Offline shell reload is verified against production assets.");
  const serviceWorkerErrors=[];
  page.on("console",(message) => { if (message.type()==="error" && /FetchEvent|Failed to convert value to 'Response'|antd\.js/.test(message.text())) serviceWorkerErrors.push(message.text()); });
  await login(page,"engineer"); const { projectId }=await fixture(page);
  await page.goto(`/site-journal?projectId=${projectId}`);
  await expect(page.getByRole("button",{ name:"＋ Ghi nhật ký",exact:true })).toBeVisible();
  await page.evaluate(async () => { await navigator.serviceWorker.ready; if (!navigator.serviceWorker.controller) await new Promise((resolve) => navigator.serviceWorker.addEventListener("controllerchange",resolve,{ once:true })); });
  await page.reload(); // warm shell assets under the controlling service worker
  await expect(page.getByRole("button",{ name:"＋ Ghi nhật ký",exact:true })).toBeVisible();
  await context.setOffline(true);
  await page.getByRole("button",{ name:"＋ Ghi nhật ký",exact:true }).click();
  let dialog=page.getByRole("dialog");
  await dialog.locator('select[name="work_item_id"]').selectOption({ index:1 });
  await dialog.getByLabel("Ngày",{ exact:true }).fill("2026-10-05");
  await dialog.getByLabel("Nội dung công việc").fill("Nhật ký ngoại tuyến có ảnh, lưu bền vững");
  await dialog.getByLabel("Nhân lực trong ngày").fill("8");
  await dialog.getByLabel("Thời tiết").fill("Nắng");
  await dialog.getByLabel("Ảnh hiện trường",{ exact:false }).setInputFiles(photo);
  await saveDialog(page,"Lưu nhật ký");
  await expect(page.locator(".ops-sync-queue")).toContainText("Nhật ký ngoại tuyến có ảnh");
  await page.reload();
  await expect(page.locator(".ops-sync-queue")).toContainText("Nhật ký ngoại tuyến có ảnh");
  await page.getByRole("button",{ name:"Sửa bản nháp" }).click();
  await expect(page.getByRole("dialog").getByRole("img",{ name:"nhat-ky.jpg" })).toBeVisible();
  await page.getByRole("dialog").getByRole("button",{ name:"Hủy",exact:true }).click();
  await context.setOffline(false); await page.evaluate(() => window.dispatchEvent(new Event("online")));
  await expect(page.locator(".ops-journal-entry")).toContainText("Nhật ký ngoại tuyến có ảnh");
  await expect(page.locator(".ops-sync-queue")).toHaveCount(0);
  await expect(page.locator(".ops-journal-entry img")).toBeVisible();
  await page.getByRole("button",{ name:"Đồng bộ / tải lại" }).click();
  await expect(page.locator(".ops-journal-entry")).toHaveCount(1);
  await page.getByRole("button",{ name:"Khóa / mở sổ" }).click();
  await page.getByRole("dialog").getByLabel("Ngày",{ exact:true }).fill("2026-10-05");
  await saveDialog(page);
  await expect(page.locator(".ops-journal-entry")).toContainText("Đã khóa sổ");
  await expect(page.locator(".ops-journal-entry").getByRole("button",{ name:"Sửa",exact:true })).toHaveCount(0);
  await page.setViewportSize({ width:390,height:844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({ path:test.info().outputPath("journal-mobile.png"),fullPage:true });
  await login(page,"admin"); await page.reload();
  await page.getByRole("button",{ name:"Khóa / mở sổ" }).click(); dialog=page.getByRole("dialog");
  await dialog.getByLabel("Ngày",{ exact:true }).fill("2026-10-05");
  await dialog.getByLabel("Thao tác").selectOption("false");
  await dialog.getByLabel("Lý do mở khóa").fill("Bổ sung biên bản công trường");
  await saveDialog(page);
  await expect(page.locator(".ops-journal-entry")).toContainText("Đã đồng bộ");
  expect(serviceWorkerErrors).toEqual([]);
});

test("real acceptance approval, payment retention, return/resubmit and PDF download",async ({ page }) => {
  const { projectId }=await fixture(page); await login(page,"admin");
  await page.goto(`/acceptance?projectId=${projectId}`);
  await page.getByRole("tab",{ name:"Khối lượng hợp đồng" }).click();
  await page.getByRole("button",{ name:"Khai báo",exact:true }).click();
  let dialog=page.getByRole("dialog");
  await dialog.getByLabel("Khối lượng hợp đồng",{ exact:true }).fill("100");
  await dialog.getByLabel("Đơn vị",{ exact:true }).fill("m³");
  await dialog.getByLabel("Đơn giá (₫)").fill("250000"); await saveDialog(page);
  await login(page,"engineer"); await page.reload();
  await page.getByRole("button",{ name:"＋ Lập phiếu nghiệm thu",exact:true }).click();
  dialog=page.getByRole("dialog");
  await dialog.locator('select[name="work_item_id"]').selectOption({ index:1 });
  await dialog.getByLabel("Kỳ / đợt nghiệm thu").fill("Nghiệm thu móng E2E");
  await dialog.getByLabel("Lũy kế hiện tại").fill("10");
  await dialog.locator('input[type="file"]').setInputFiles(photo);
  await expect(dialog.getByText("Ảnh đính kèm (1)")).toBeVisible();
  await saveDialog(page);
  let row=page.getByRole("row").filter({ hasText:"Nghiệm thu móng E2E" });
  await transition(page,row,"Trình duyệt");
  await login(page,"viewer"); await page.reload(); await transition(page,row,"Duyệt");
  await expect(row).toContainText("Đã duyệt");
  await page.screenshot({ path:test.info().outputPath("acceptance-desktop.png"),fullPage:true });
  await login(page,"accountant"); await page.goto(`/payments?projectId=${projectId}`);
  await page.getByRole("button",{ name:"＋ Tạo đề nghị thanh toán",exact:true }).click();
  dialog=page.getByRole("dialog"); await dialog.getByLabel("Kỳ thanh toán").fill("Thanh toán móng E2E");
  await dialog.getByLabel("Tỷ lệ tạm giữ (%)").fill("10");
  await dialog.getByRole("checkbox",{ name:/Nghiệm thu móng E2E/ }).check(); await saveDialog(page);
  row=page.getByRole("row").filter({ hasText:"Thanh toán móng E2E" });
  await expect(row).toContainText("2.500.000"); await expect(row).toContainText("250.000"); await expect(row).toContainText("2.250.000");
  await transition(page,row,"Trình duyệt"); await login(page,"viewer"); await page.reload();
  await row.getByRole("button",{ name:"Trả lại",exact:true }).click();
  await page.getByRole("dialog").getByLabel("Lý do trả lại").fill("Bổ sung chứng từ"); await saveDialog(page,"Trả lại phiếu");
  await login(page,"accountant"); await page.goto(`/notifications?projectId=${projectId}`);
  await page.getByRole("button",{ name:"Đánh dấu tất cả đã đọc" }).click();
  await expect(page.getByRole("heading",{ name:"Hộp thông báo (0 chưa đọc)" })).toBeVisible();
  await page.goto(`/payments?projectId=${projectId}`); await row.getByRole("button",{ name:"Sửa",exact:true }).click(); await saveDialog(page);
  await transition(page,row,"Trình duyệt"); await login(page,"viewer"); await page.reload(); await transition(page,row,"Duyệt");
  await expect(row).toContainText("Đã duyệt");
  await page.goto(`/reports?projectId=${projectId}`);
  await page.locator(".ops-toolbar select").selectOption({ index:1 });
  const downloading=page.waitForEvent("download"); await page.getByRole("button",{ name:"Tải hồ sơ PDF" }).click();
  const download=await downloading; const bytes=await readFile(await download.path()); expect(bytes.subarray(0,5).toString()).toBe("%PDF-");
  await page.screenshot({ path:test.info().outputPath("reports-desktop.png"),fullPage:true });
  await login(page,"worker"); await page.goto(`/payments?projectId=${projectId}`);
  await expect(page.getByRole("alert")).toBeVisible();
});

test("budget versions, real costs, nonnegative inventory, settings and photo gallery",async ({ page }) => {
  const { projectId,workItemId }=await fixture(page); await login(page,"admin");
  await page.goto(`/costs-materials?projectId=${projectId}`);
  await page.getByRole("button",{ name:"Dự toán",exact:true }).click();
  await page.getByRole("dialog").getByLabel("Giá trị dự toán (₫)").fill("10000000"); await saveDialog(page);
  await page.getByRole("tab",{ name:"Thực chi",exact:true }).click();
  await page.getByRole("button",{ name:"＋ Ghi thực chi",exact:true }).click();
  let dialog=page.getByRole("dialog"); await dialog.getByLabel("Hạng mục lá").selectOption(String(workItemId));
  await dialog.getByLabel("Loại chi").fill("Vật tư móng"); await dialog.getByLabel("Số tiền (₫)").fill("9000000"); await saveDialog(page);
  await page.getByRole("tab",{ name:"Dự toán",exact:true }).click(); await expect(page.getByText("Chi cao, nghiệm thu thấp")).toBeVisible();
  await page.getByRole("button",{ name:"Lịch sử",exact:true }).click(); await expect(page.getByRole("dialog")).toContainText("10.000.000"); await page.getByRole("dialog").getByRole("button",{ name:"Đóng",exact:true }).click();
  await page.getByRole("tab",{ name:"Vật tư",exact:true }).click(); await page.getByRole("button",{ name:"＋ Thêm vật tư",exact:true }).click();
  dialog=page.getByRole("dialog"); await dialog.getByLabel("Tên vật tư").fill("Thép móng E2E"); await dialog.getByLabel("Đơn vị",{ exact:true }).fill("kg"); await saveDialog(page);
  await page.getByRole("button",{ name:"Nhập kho",exact:true }).click(); await page.getByRole("dialog").getByLabel("Khối lượng",{ exact:true }).fill("100"); await saveDialog(page);
  await page.getByRole("button",{ name:"Xuất kho",exact:true }).click(); dialog=page.getByRole("dialog");
  await dialog.getByLabel("Hạng mục lá").selectOption(String(workItemId)); await dialog.getByLabel("Khối lượng",{ exact:true }).fill("101");
  await dialog.getByRole("button",{ name:"Lưu",exact:true }).click(); await expect(dialog.getByRole("alert")).toContainText("Không đủ tồn kho");
  await dialog.getByLabel("Khối lượng",{ exact:true }).fill("20"); await saveDialog(page);
  await expect(page.getByRole("row").filter({ has:page.getByRole("button",{ name:"Xuất kho",exact:true }) })).toContainText("80");
  await page.screenshot({ path:test.info().outputPath("inventory-desktop.png"),fullPage:true });
  await page.goto(`/settings?projectId=${projectId}`); await page.getByRole("button",{ name:"Cấu hình",exact:true }).click();
  dialog=page.getByRole("dialog"); await dialog.getByLabel("Vĩ độ").fill("21"); await dialog.getByLabel("Kinh độ").fill("105.8"); await dialog.getByLabel("Bán kính (m)").fill("500"); await saveDialog(page);
  await page.getByRole("checkbox",{ name:"Mốc tiến độ quá hạn" }).click(); await expect(page.getByRole("checkbox",{ name:"Mốc tiến độ quá hạn" })).not.toBeChecked(); await page.reload(); await expect(page.getByRole("checkbox",{ name:"Mốc tiến độ quá hạn" })).not.toBeChecked();
  await page.goto(`/site-photos?projectId=${projectId}`); await page.getByRole("button",{ name:"＋ Tải ảnh hiện trường",exact:true }).click();
  dialog=page.getByRole("dialog"); await dialog.locator('select[name="work_item_id"]').selectOption(String(workItemId)); await dialog.locator('input[type="file"]').setInputFiles(photo); await saveDialog(page);
  await expect(page.locator(".ops-photo-grid img").first()).toBeVisible();
  await page.setViewportSize({ width:390,height:844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({ path:test.info().outputPath("photos-mobile.png"),fullPage:true });
  await page.goto(`/audit-logs?projectId=${projectId}`); await page.getByLabel("Phân hệ").selectOption("materials");
  await expect(page.getByRole("table")).toContainText("Vật tư"); await page.getByRole("button",{ name:"Xem thay đổi" }).first().click(); await expect(page.getByRole("dialog")).toContainText("quantity");
});
