import { useState } from "react";
import { useSearchParams } from "react-router-dom";
import DashboardLayout from "../components/DashboardLayout";
import { CostOverview } from "../components/ModuleInsights";
import RecordEditor from "../components/RecordEditor";
import { Empty,Modal,NoProject,Notice,RemoteState } from "../components/OperationsUI";
import useRemote from "../hooks/useRemote";
import { api,dateLabel,numberLabel,projectPath,today } from "../services/operationsApi";
import { moneyLabel } from "../services/siteApi";
import { validProjectId } from "../services/navigation";
import "../styles/SiteModules.css";

const tabs = [["budget","Dự toán"],["costs","Thực chi"],["materials","Vật tư"],["compare","Đối chiếu"]];
function CostEditor({ projectId,data,modal,onClose,onSaved }) {
  const leaves = data.items.filter((item) => item.is_leaf).map((item) => ({ value:item.id,label:item.title }));
  const materialOptions = data.materials.map((item) => ({ value:item.id,label:`${item.name} (${item.unit})` }));
  const itemField = { name:"work_item_id",label:"Hạng mục lá",type:"select",options:leaves };
  const note = { name:"notes",label:"Ghi chú",type:"textarea",required:false,maxLength:2000 };
  const common = { day:today(),notes:"",client_uuid:crypto.randomUUID() };
  const definitions = {
    budget:{ title:"Lưu phiên bản dự toán",path:"/budgets",initial:{ amount:modal.record?.budget || "",notes:"",work_item_id:modal.record?.id || "",version:modal.record?.version || 0 },fields:[{ ...itemField,options:modal.record ? leaves.filter((item) => item.value === modal.record.id) : leaves },{ name:"amount",label:"Giá trị dự toán (₫)",type:"number",min:0,step:"0.01" },note] },
    cost:{ title:"Ghi nhận thực chi",path:"/costs",initial:{ ...common,work_item_id:"",amount:"",type:"" },fields:[{ name:"day",label:"Ngày chi",type:"date" },{ ...itemField,required:false,placeholder:"Chờ phân bổ" },{ name:"type",label:"Loại chi",maxLength:100 },{ name:"amount",label:"Số tiền (₫)",type:"number",min:"0.01",step:"0.01" },note] },
    allocate:{ title:"Phân bổ khoản chi",path:`/costs/${modal.record?.id}/allocate`,method:"PATCH",initial:{ work_item_id:modal.record?.work_item_id || "",revision:modal.record?.revision },fields:[itemField] },
    material:{ title:"Thêm vật tư",path:"/materials",initial:{ name:"",unit:"" },fields:[{ name:"name",label:"Tên vật tư" },{ name:"unit",label:"Đơn vị",maxLength:30 }] },
    inventory:{ title:modal.direction === "in" ? "Lập phiếu nhập kho" : "Lập phiếu xuất kho",path:"/inventory",initial:{ ...common,direction:modal.direction,material_id:modal.record?.id || "",work_item_id:"",quantity:"" },fields:[{ name:"material_id",label:"Vật tư",type:"select",options:materialOptions },{ name:"quantity",label:"Khối lượng",type:"number",min:"0.0001",step:"0.0001" },{ ...itemField,required:modal.direction === "out",placeholder:modal.direction === "out" ? "Chọn hạng mục nhận" : "Không gắn hạng mục" },{ name:"day",label:"Ngày nhập / xuất",type:"date" },note] },
    norm:{ title:"Cấu hình định mức vật tư",path:"/material-norms",method:"PUT",initial:{ work_item_id:"",material_id:"",quantity_per_unit:"" },fields:[itemField,{ name:"material_id",label:"Vật tư",type:"select",options:materialOptions },{ name:"quantity_per_unit",label:"Lượng vật tư / 1 đơn vị nghiệm thu",type:"number",min:"0.0001",step:"0.0001" }] },
    import:{ title:"Import thực chi từ CSV",path:"/costs/import",initial:{ csv:"",client_uuid:crypto.randomUUID() },fields:[] },
  };
  const definition = definitions[modal.kind];
  return <RecordEditor title={definition.title} initial={definition.initial} fields={definition.fields} onClose={onClose} onSaved={onSaved} submit={(values) => {
    const body = { ...values };
    if ("work_item_id" in body) body.work_item_id = body.work_item_id ? Number(body.work_item_id) : null;
    if ("material_id" in body) body.material_id = Number(body.material_id);
    return api(projectPath(projectId,definition.path),{ method:definition.method || "POST",body });
  }}>
    {(values,change) => modal.kind === "import" ? <><Notice>CSV dùng các cột: day, amount, type, work_item_id, notes. Để trống work_item_id cho khoản chi chờ phân bổ. Ngày định dạng YYYY-MM-DD; số dùng dấu chấm thập phân.</Notice><label className="ops-field"><span>Chọn CSV (tối đa 1 MB)</span><input type="file" accept=".csv,text/csv" onChange={async (event) => { const file = event.target.files[0]; if (file && file.size <= 1024*1024) change("csv",await file.text()); }} /></label><label className="ops-field"><span>Nội dung CSV</span><textarea required value={values.csv} onChange={(event) => change("csv",event.target.value)} placeholder="day,amount,type,work_item_id,notes" /></label></> : modal.kind === "inventory" ? <Notice>Tồn hiện tại: {numberLabel(data.materials.find((entry) => entry.id === Number(values.material_id))?.stock)} {data.materials.find((entry) => entry.id === Number(values.material_id))?.unit}</Notice> : modal.kind === "budget" ? <Notice>Mỗi lần lưu tạo một phiên bản mới. Lịch sử dự toán được giữ lại.</Notice> : null}
  </RecordEditor>;
}
function ProjectCosts({ projectId }) {
  const state = useRemote(projectPath(projectId,"/costs")); const data = state.data;
  const [tab,setTab] = useState("budget"); const [modal,setModal] = useState(null); const [message,setMessage] = useState(""); const [unallocated,setUnallocated] = useState(false);
  function saved(result) { setModal(null); setMessage(result.count !== undefined ? `Đã import ${result.count} khoản chi.` : "Đã lưu dữ liệu."); state.reload(); }
  const costs = (data?.costs || []).filter((entry) => !unallocated || !entry.work_item_id);
  const rootRows = (data?.comparison || []).filter((item) => !item.parent_id);
  return <><Notice tone="success">{message}</Notice><RemoteState state={state}>{data && <><CostOverview data={data} rootRows={rootRows} />
    <section className="ops-card"><div className="ops-tabs" role="tablist" aria-label="Chi phí và vật tư">{tabs.map(([key,label]) => <button role="tab" aria-selected={tab === key} key={key} onClick={() => setTab(key)}>{label}</button>)}</div>
      {tab === "budget" && <><div className="ops-card-head"><div><h2>Dự toán và thực chi theo hạng mục</h2><p>Tổng hạng mục cha được cộng từ con. Cảnh báo khi chi phí vượt 80% dự toán mà nghiệm thu chưa đạt 80%.</p></div><button className="ops-btn" onClick={state.reload}>Tải lại</button></div>{data.comparison.length ? <div className="ops-table-scroll"><table className="ops-table"><thead><tr><th>Hạng mục</th><th>Dự toán (₫)</th><th>Thực chi (₫)</th><th>Sử dụng</th><th>Nghiệm thu</th><th>Còn lại (₫)</th><th>Thao tác</th></tr></thead><tbody>{data.comparison.map((row) => <tr key={row.id} className={row.warning ? "ops-warning-row" : ""}><td>{row.parent_id ? "↳ " : ""}{row.title}{row.warning && <small>Chi cao, nghiệm thu thấp</small>}</td><td className="ops-money">{moneyLabel(row.budget)}{row.version > 0 && <small>Phiên bản {row.version}</small>}</td><td className="ops-money">{moneyLabel(row.actual)}</td><td>{row.usage_percent == null ? "—" : `${row.usage_percent.toFixed(1)}%`}</td><td>{row.accepted_percent == null ? "—" : `${row.accepted_percent.toFixed(1)}%`}</td><td className="ops-money">{moneyLabel(row.variance)}</td><td><div className="ops-row-actions">{row.is_leaf && data.can_edit && <button className="ops-btn ops-small" onClick={() => setModal({ kind:"budget",record:row })}>Dự toán</button>}{row.version > 0 && <button className="ops-btn ops-small" onClick={() => setModal({ kind:"history",record:row })}>Lịch sử</button>}</div></td></tr>)}</tbody></table></div> : <Empty>Chưa có hạng mục để lập dự toán.</Empty>}</>}
      {tab === "costs" && <><div className="ops-card-head"><div><h2>Nhật ký thực chi</h2><p>Ghi nhận chi phí phát sinh và phân bổ vào hạng mục.</p></div>{data.can_edit && <div className="ops-actions"><button className="ops-btn" onClick={() => setModal({ kind:"import" })}>Import CSV</button><button className="ops-btn ops-create" onClick={() => setModal({ kind:"cost" })}>＋ Ghi thực chi</button></div>}</div><label className="ops-checkbox"><input type="checkbox" checked={unallocated} onChange={(event) => setUnallocated(event.target.checked)} />Chỉ hiện khoản chờ phân bổ</label>{costs.length ? <div className="ops-table-scroll"><table className="ops-table"><thead><tr><th>Ngày</th><th>Hạng mục</th><th>Loại chi</th><th>Số tiền (₫)</th><th>Ghi chú</th>{data.can_edit && <th>Thao tác</th>}</tr></thead><tbody>{costs.map((cost) => <tr key={cost.id}><td>{dateLabel(cost.day)}</td><td>{cost.item_name || <span className="ops-badge ops-badge-orange">Chờ phân bổ</span>}</td><td>{cost.type}</td><td className="ops-money">{moneyLabel(cost.amount)}</td><td>{cost.notes || "—"}</td>{data.can_edit && <td><button className="ops-btn ops-small" onClick={() => setModal({ kind:"allocate",record:cost })}>Phân bổ</button></td>}</tr>)}</tbody></table></div> : <Empty>Chưa có khoản chi phù hợp.</Empty>}</>}
      {tab === "materials" && <><div className="ops-card-head"><div><h2>Vật tư và tồn kho</h2><p>Phiếu xuất chỉ được lưu khi tồn kho đủ.</p></div>{data.can_edit && <button className="ops-btn ops-create" onClick={() => setModal({ kind:"material" })}>＋ Thêm vật tư</button>}</div>{data.materials.length ? <div className="ops-table-scroll"><table className="ops-table"><thead><tr><th>Vật tư</th><th>Đơn vị</th><th>Tồn kho</th>{data.can_edit && <th>Thao tác</th>}</tr></thead><tbody>{data.materials.map((material) => <tr key={material.id}><td>{material.name}</td><td>{material.unit}</td><td>{numberLabel(material.stock)}</td>{data.can_edit && <td><div className="ops-row-actions"><button className="ops-btn ops-small" onClick={() => setModal({ kind:"inventory",direction:"in",record:material })}>Nhập kho</button><button className="ops-btn ops-small" onClick={() => setModal({ kind:"inventory",direction:"out",record:material })}>Xuất kho</button></div></td>}</tr>)}</tbody></table></div> : <Empty>Chưa có vật tư trong danh mục.</Empty>}<h2 style={{ marginTop:28 }}>Lịch sử nhập / xuất</h2>{data.inventory.length ? <div className="ops-table-scroll"><table className="ops-table"><thead><tr><th>Ngày</th><th>Vật tư</th><th>Loại phiếu</th><th>Khối lượng</th><th>Hạng mục</th><th>Người lập</th></tr></thead><tbody>{data.inventory.map((entry) => <tr key={entry.id}><td>{dateLabel(entry.day)}</td><td>{entry.material_name}</td><td><span className={`ops-badge ops-badge-${entry.direction === "in" ? "green" : "orange"}`}>{entry.direction === "in" ? "Nhập" : "Xuất"}</span></td><td>{numberLabel(entry.quantity)} {entry.unit}</td><td>{entry.item_name || "—"}</td><td>{entry.author}</td></tr>)}</tbody></table></div> : <Empty>Chưa có giao dịch kho.</Empty>}</>}
      {tab === "compare" && <><div className="ops-card-head"><div><h2>Đối chiếu vật tư theo nghiệm thu</h2><p>Định mức do dự án cấu hình. Chênh lệch dương được đánh dấu để kiểm tra.</p></div>{data.can_edit && <button className="ops-btn ops-create" onClick={() => setModal({ kind:"norm" })}>＋ Cấu hình định mức</button>}</div>{data.reconciliation.length ? <div className="ops-table-scroll"><table className="ops-table"><thead><tr><th>Hạng mục / vật tư</th><th>Đã xuất</th><th>Định mức</th><th>Khối lượng nghiệm thu</th><th>Theo định mức</th><th>Chênh lệch</th></tr></thead><tbody>{data.reconciliation.map((row) => <tr key={`${row.work_item_id}-${row.material_id}`} className={Number(row.variance) > 0 ? "ops-warning-row" : ""}><td>{row.item_name}<small>{row.material_name} · {row.unit}</small></td><td>{numberLabel(row.issued)}</td><td>{row.quantity_per_unit == null ? "Chưa cấu hình" : numberLabel(row.quantity_per_unit)}</td><td>{numberLabel(row.accepted_quantity)}</td><td>{row.allowed == null ? "—" : numberLabel(row.allowed)}</td><td>{row.variance == null ? "—" : numberLabel(row.variance)}</td></tr>)}</tbody></table></div> : <Empty>Cấu hình định mức hoặc ghi nhận xuất kho để đối chiếu.</Empty>}</>}
    </section></>}</RemoteState>{modal && modal.kind !== "history" && <CostEditor projectId={projectId} data={data} modal={modal} onClose={() => setModal(null)} onSaved={saved} />}{modal?.kind === "history" && <Modal title={`Lịch sử dự toán · ${modal.record.title}`} onClose={() => setModal(null)}><table className="ops-table"><thead><tr><th>Phiên bản</th><th>Dự toán (₫)</th><th>Ghi chú</th></tr></thead><tbody>{data.budgets.filter((budget) => budget.work_item_id === modal.record.id).map((budget) => <tr key={budget.id}><td>v{budget.version}<small>{new Date(budget.created_at).toLocaleString("vi-VN")}</small></td><td>{moneyLabel(budget.amount)}</td><td>{budget.notes || "—"}</td></tr>)}</tbody></table></Modal>}</>;
}
export default function CostsMaterials() { const [params] = useSearchParams(); const projectId = params.get("projectId"); return <DashboardLayout title="Chi phí & vật tư" description="Theo dõi dự toán, thực chi, nhập xuất kho và mức sử dụng vật tư theo hạng mục.">{validProjectId(projectId) ? <ProjectCosts key={projectId} projectId={projectId} /> : <NoProject />}</DashboardLayout>; }
