import { useState } from "react";
import { useSearchParams } from "react-router-dom";
import DashboardLayout from "../components/DashboardLayout";
import { PaymentOverview } from "../components/ModuleInsights";
import { WorkflowStrip } from "../components/OperationsVisuals";
import RecordEditor from "../components/RecordEditor";
import WorkflowAction from "../components/WorkflowAction";
import { Empty,Modal,NoProject,Notice,RemoteState } from "../components/OperationsUI";
import useRemote from "../hooks/useRemote";
import { api,dateLabel,numberLabel,projectPath,today } from "../services/operationsApi";
import { moneyLabel,workflowLabels,workflowTones } from "../services/siteApi";
import { validProjectId } from "../services/navigation";
import "../styles/SiteModules.css";

function PaymentForm({ projectId,data,record,onClose,onSaved }) {
  const initial = record ? { ...record,acceptance_ids:record.items.map((item) => item.acceptance_id) } : { period:"",day:today(),retention_rate:"0",acceptance_ids:[] };
  const available = data.acceptances.filter((entry) => entry.status === "approved" && (!entry.in_payment || initial.acceptance_ids.includes(entry.id)));
  return <RecordEditor title={record ? "Sửa đề nghị thanh toán" : "Tạo đề nghị thanh toán"} initial={initial} fields={[{ name:"period",label:"Kỳ thanh toán" },{ name:"day",label:"Ngày đề nghị",type:"date" },{ name:"retention_rate",label:"Tỷ lệ tạm giữ (%)",type:"number",min:0,max:100,step:"0.01" }]} onClose={onClose} onSaved={onSaved} submit={(values) => api(projectPath(projectId,`/payments${record ? `/${record.id}` : ""}`),{ method:record ? "PUT" : "POST",body:values })}>
    {(values,change) => <><p className="ops-muted">Chọn phiếu nghiệm thu đã duyệt. Mỗi phiếu chỉ được dùng trong một đề nghị.</p><div className="ops-check-list">{available.length ? available.map((entry) => <label key={entry.id}><input type="checkbox" checked={values.acceptance_ids.includes(entry.id)} onChange={(event) => change("acceptance_ids",event.target.checked ? [...values.acceptance_ids,entry.id] : values.acceptance_ids.filter((id) => id !== entry.id))} /><span>#{entry.id} · {entry.period}<small>{entry.item_name} · {numberLabel(entry.quantity)} {entry.unit} × {moneyLabel(entry.unit_price)} ₫</small></span></label>) : <Empty>Không có phiếu nghiệm thu đã duyệt chưa dùng.</Empty>}</div><Notice>Giá trị, tiền tạm giữ và thực trả được tính từ các phiếu nghiệm thu khi lưu.</Notice></>}
  </RecordEditor>;
}
function ProjectPayments({ projectId }) {
  const state = useRemote(projectPath(projectId,"/payments")); const data = state.data;
  const [status,setStatus] = useState(""); const [modal,setModal] = useState(null); const [message,setMessage] = useState("");
  const requests = (data?.requests || []).filter((entry) => !status || entry.status === status);
  const approved = (data?.requests || []).filter((entry) => entry.status === "approved");
  function saved() { setModal(null); setMessage("Đã lưu đề nghị thanh toán."); state.reload(); }
  return <><Notice tone="success">{message}</Notice><RemoteState state={state}>{data && <><PaymentOverview approved={approved} /><WorkflowStrip records={data.requests} /><section className="ops-card"><div className="ops-card-head"><div><h2>Đề nghị thanh toán</h2><p>Chỉ sử dụng khối lượng đã được nghiệm thu và phê duyệt.</p></div>{data.can_edit && <button className="ops-btn ops-create" onClick={() => setModal({ kind:"form" })}>＋ Tạo đề nghị thanh toán</button>}</div><div className="ops-toolbar"><label>Trạng thái<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Tất cả</option>{Object.entries(workflowLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><button className="ops-btn" onClick={state.reload}>Tải lại</button></div>
    {requests.length ? <div className="ops-table-scroll"><table className="ops-table"><thead><tr><th>Kỳ thanh toán</th><th>Ngày</th><th>Thành tiền (₫)</th><th>Tạm giữ (₫)</th><th>Thực trả (₫)</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{requests.map((entry) => <tr key={entry.id}><td>{entry.period}<small>{entry.author}</small></td><td>{dateLabel(entry.day)}</td><td className="ops-money">{moneyLabel(entry.gross)}</td><td className="ops-money">{moneyLabel(entry.retained)}<small>{entry.retention_rate}%</small></td><td className="ops-money">{moneyLabel(entry.net)}</td><td><span className={`ops-badge ops-badge-${workflowTones[entry.status]}`}>{workflowLabels[entry.status]}</span></td><td><div className="ops-row-actions"><button className="ops-btn ops-small" onClick={() => setModal({ kind:"detail",record:entry })}>Chi tiết</button>{data.can_edit && ["draft","returned"].includes(entry.status) && <button className="ops-btn ops-small" onClick={() => setModal({ kind:"form",record:entry })}>Sửa</button>}{data.can_edit && entry.status === "draft" && <button className="ops-btn ops-small" onClick={() => setModal({ kind:"workflow",record:entry,action:"submit" })}>Trình duyệt</button>}{data.can_approve && entry.status === "submitted" && <><button className="ops-btn ops-small ops-primary" onClick={() => setModal({ kind:"workflow",record:entry,action:"approve" })}>Duyệt</button><button className="ops-btn ops-small ops-danger" onClick={() => setModal({ kind:"workflow",record:entry,action:"return" })}>Trả lại</button></>}</div></td></tr>)}</tbody></table></div> : <Empty>Chưa có đề nghị thanh toán phù hợp.</Empty>}
    </section></>}</RemoteState>{modal?.kind === "form" && <PaymentForm projectId={projectId} data={data} record={modal.record} onClose={() => setModal(null)} onSaved={saved} />}{modal?.kind === "workflow" && <WorkflowAction {...modal} module="payments" projectId={projectId} onClose={() => setModal(null)} onSaved={saved} />}
    {modal?.kind === "detail" && <Modal variant="drawer" title={`Thanh toán · ${modal.record.period}`} onClose={() => setModal(null)}><Notice tone="warning">{modal.record.return_reason}</Notice><div className="ops-table-scroll"><table className="ops-table"><thead><tr><th>Hạng mục / phiếu</th><th>Khối lượng</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>{modal.record.items.map((item) => <tr key={item.acceptance_id}><td>{item.item_name}<small>Phiếu #{item.acceptance_id}</small></td><td>{numberLabel(item.quantity)} {item.unit}</td><td>{moneyLabel(item.unit_price)}</td><td>{moneyLabel(item.amount)}</td></tr>)}</tbody></table></div><dl className="ops-details-list"><dt>Thành tiền</dt><dd>{moneyLabel(modal.record.gross)} ₫</dd><dt>Tạm giữ</dt><dd>{moneyLabel(modal.record.retained)} ₫ ({modal.record.retention_rate}%)</dd><dt>Thực trả</dt><dd>{moneyLabel(modal.record.net)} ₫</dd><dt>Người duyệt</dt><dd>{modal.record.approver || "Chưa duyệt"}</dd></dl></Modal>}
  </>;
}
export default function Payments() { const [params] = useSearchParams(); const projectId = params.get("projectId"); return <DashboardLayout title="Thanh toán" description="Lập đề nghị từ nghiệm thu đã duyệt, theo dõi tạm giữ và phê duyệt thanh toán.">{validProjectId(projectId) ? <ProjectPayments key={projectId} projectId={projectId} /> : <NoProject />}</DashboardLayout>; }
