import { useState } from "react";
import { Link,useSearchParams } from "react-router-dom";
import DashboardLayout from "../components/DashboardLayout";
import Icon from "../components/OperationsIcon";
import { SectionHeading } from "../components/OperationsVisuals";
import "../styles/ActivityPolish.css";
import RecordEditor from "../components/RecordEditor";
import { NoProject,Notice,RemoteState } from "../components/OperationsUI";
import useRemote from "../hooks/useRemote";
import { api,dateLabel,projectPath,projectStatuses } from "../services/operationsApi";
import { scopedLink,validProjectId } from "../services/navigation";
import "../styles/SiteModules.css";

const eventLabels = { acceptance_returned:"Phiếu nghiệm thu bị trả lại",payment_returned:"Đề nghị thanh toán bị trả lại",milestone_overdue:"Mốc tiến độ quá hạn" };
function ProjectSettings({ projectId,onAccountChange }) {
  const state = useRemote(projectPath(projectId,"/settings")); const account = useRemote("/auth/me");
  const [modal,setModal] = useState(null); const [busy,setBusy] = useState(false); const [error,setError] = useState(""); const [message,setMessage] = useState("");
  const [preferenceOverrides,setPreferenceOverrides] = useState({});
  async function preference(type,enabled) {
    setBusy(true); setError(""); setPreferenceOverrides((current) => ({ ...current,[type]:enabled }));
    try { await api(projectPath(projectId,"/preferences"),{ method:"PUT",body:{ type,email_enabled:enabled } }); state.reload(); }
    catch (failure) { setError(failure.message); setPreferenceOverrides((current) => { const next={ ...current }; delete next[type]; return next; }); } finally { setBusy(false); }
  }
  function saved() { setModal(null); setMessage("Đã lưu cài đặt."); state.reload(); account.reload(); onAccountChange(); }
  const data = state.data;
  return <><Notice tone="error">{error}</Notice><Notice tone="success">{message}</Notice><RemoteState state={state}>{data && <div className="settings-layout"><aside className="ops-card settings-nav"><span className="settings-avatar">{account.data?.user.fullname?.slice(0,1) || "—"}</span><strong>{account.data?.user.fullname || "Tài khoản"}</strong><small>{account.data?.user.email}</small><nav aria-label="Nhóm cài đặt">{[["account","users","Tài khoản"],["email","bell","Thông báo"],["project","building","Dự án"],["location","pin","Vị trí công trường"]].map(([id,icon,label])=><a href={`#settings-${id}`} key={id}><Icon name={icon} size={18}/>{label}<Icon name="right" size={14}/></a>)}</nav><p>Cài đặt được áp dụng theo dự án và quyền truy cập của bạn.</p></aside><div className="settings-sections"><section className="ops-card" id="settings-account"><div className="ops-card-head"><SectionHeading icon="users" title="Tài khoản" description="Thông tin hiển thị trong dự án"/>{account.data && <button className="ops-btn ops-small" onClick={() => setModal({ kind:"profile" })}>Chỉnh sửa tên</button>}</div><RemoteState state={account}><dl className="ops-details-list"><dt>Họ tên</dt><dd>{account.data?.user.fullname}</dd><dt>Email</dt><dd>{account.data?.user.email}</dd></dl></RemoteState><p className="ops-muted">Email đăng nhập chỉ hiển thị tại đây.</p></section>
    <section className="ops-card" id="settings-email"><SectionHeading icon="bell" tone="orange" title="Email thông báo" description="Tùy chọn nhận cập nhật cho tài khoản"/><p className="ops-muted">Chọn loại sự kiện muốn nhận. Email chỉ nêu sự kiện và đường dẫn hồ sơ.</p>{!data.email_configured && <Notice tone="warning">Chưa cấu hình máy chủ gửi email. Thông báo trong hệ thống vẫn hoạt động; tùy chọn email của bạn được lưu.</Notice>}<div className="ops-settings-form">{data.preferences.map((entry) => <label className="ops-checkbox" key={entry.type}><input type="checkbox" checked={preferenceOverrides[entry.type] ?? entry.email_enabled} disabled={busy} onChange={(event) => preference(entry.type,event.target.checked)} />{eventLabels[entry.type]}</label>)}</div></section>
    <section className="ops-card" id="settings-project"><SectionHeading icon="building" title="Thông tin dự án" description="Thông tin cơ bản và lịch thi công"/><dl className="ops-details-list"><dt>Tên</dt><dd>{data.project.name}</dd><dt>Địa điểm</dt><dd>{data.project.location || "Chưa cập nhật"}</dd><dt>Khởi công</dt><dd>{dateLabel(data.project.start_date)}</dd><dt>Trạng thái</dt><dd>{projectStatuses[data.project.status]}</dd></dl><div className="ops-actions"><Link className="ops-btn" to={scopedLink("/projects",projectId)}>Quản lý dự án</Link><Link className="ops-btn" to={scopedLink("/calendar",projectId)}>Lịch làm việc</Link></div></section>
    <section className="ops-card" id="settings-location"><div className="ops-card-head"><SectionHeading icon="pin" tone="green" title="Vị trí công trường" description="Phạm vi dùng để đối chiếu ảnh hiện trường"/>{data.can_manage && <button className="ops-btn ops-small" onClick={() => setModal({ kind:"site" })}>Cấu hình</button>}</div><p className="ops-muted">Dùng tọa độ EXIF để đánh dấu ảnh ngoài phạm vi, không tự động từ chối ảnh.</p><div className="settings-location-info"><div className="settings-location-symbol" aria-hidden="true"><Icon name="pin" size={35}/></div><dl className="ops-details-list"><dt>Vĩ độ</dt><dd>{data.site?.latitude ?? "Chưa cấu hình"}</dd><dt>Kinh độ</dt><dd>{data.site?.longitude ?? "Chưa cấu hình"}</dd><dt>Bán kính</dt><dd>{data.site?.radius_m ? `${data.site.radius_m} m` : "Chưa cấu hình"}</dd></dl></div><Link className="ops-btn" to={scopedLink("/site-photos",projectId)}>Xem ảnh hiện trường</Link></section>
  </div></div>}</RemoteState>
    {modal?.kind === "profile" && <RecordEditor title="Cập nhật tên tài khoản" initial={{ fullname:account.data.user.fullname }} fields={[{ name:"fullname",label:"Họ tên" }]} onClose={() => setModal(null)} onSaved={saved} submit={(values) => api(projectPath(projectId,"/account"),{ method:"PATCH",body:values })} />}
    {modal?.kind === "site" && <RecordEditor title="Vị trí và bán kính công trường" initial={data.site || { latitude:"",longitude:"",radius_m:"",revision:0 }} fields={[{ name:"latitude",label:"Vĩ độ",type:"number",min:-90,max:90,step:"any",required:false },{ name:"longitude",label:"Kinh độ",type:"number",min:-180,max:180,step:"any",required:false },{ name:"radius_m",label:"Bán kính (m)",type:"number",min:1,step:1,required:false }]} onClose={() => setModal(null)} onSaved={saved} submit={(values) => api(projectPath(projectId,"/settings"),{ method:"PUT",body:{ revision:values.revision,latitude:values.latitude === "" ? null : Number(values.latitude),longitude:values.longitude === "" ? null : Number(values.longitude),radius_m:values.radius_m === "" ? null : Number(values.radius_m) } })}><Notice>Để trống cả ba giá trị để gỡ cấu hình. Ảnh không có GPS vẫn được lưu.</Notice></RecordEditor>}
  </>;
}
export default function Settings() { const [params] = useSearchParams(); const projectId = params.get("projectId"); const [revision,setRevision] = useState(0); return <DashboardLayout title="Cài đặt" description="Quản lý tài khoản, tùy chọn thông báo và cấu hình vận hành công trường." refreshKey={revision}>{validProjectId(projectId) ? <ProjectSettings key={projectId} projectId={projectId} onAccountChange={() => setRevision((value) => value+1)} /> : <NoProject />}</DashboardLayout>; }
