import { useState } from "react";
import { useSearchParams } from "react-router-dom";
import DashboardLayout from "../components/DashboardLayout";
import { PhotoOverview } from "../components/ModuleInsights";
import RecordEditor from "../components/RecordEditor";
import { Empty,Modal,NoProject,Notice,RemoteState } from "../components/OperationsUI";
import useRemote from "../hooks/useRemote";
import { projectPath } from "../services/operationsApi";
import { photoUrl,uploadPhoto } from "../services/siteApi";
import { validProjectId } from "../services/navigation";
import "../styles/SiteModules.css";

function ProjectPhotos({ projectId }) {
  const state = useRemote(projectPath(projectId,"/photos")); const lookup = useRemote(projectPath(projectId,"/lookup"));
  const [modal,setModal] = useState(null); const [message,setMessage] = useState("");
  const [filters,setFilters] = useState({ day:"",item:"",uploader:"",suspicious:"" }); const [page,setPage] = useState(1);
  const photos = state.data?.photos || [];
  const uploaders = [...new Map(photos.map((photo) => [photo.uploaded_by,photo.uploader])).entries()];
  const filtered = photos.filter((photo) => (!filters.day || new Intl.DateTimeFormat("en-CA",{ timeZone:"Asia/Ho_Chi_Minh" }).format(new Date(photo.created_at)) === filters.day) && (!filters.item || photo.work_item_id === Number(filters.item)) && (!filters.uploader || photo.uploaded_by === Number(filters.uploader)) && (!filters.suspicious || (filters.suspicious === "yes" ? photo.suspicious : !photo.suspicious)));
  const pages = Math.max(1,Math.ceil(filtered.length/24)); const currentPage = Math.min(page,pages);
  const canUpload = ["admin","project_manager","manager","engineer","worker"].includes(state.data?.member_role);
  return <><Notice tone="success">{message}</Notice><RemoteState state={state}><PhotoOverview photos={photos} onReview={()=>{setFilters({...filters,suspicious:"yes"});setPage(1);}}/><section className="ops-card"><div className="ops-card-head"><div><h2>Thư viện ảnh ({filtered.length})</h2><p>Giữ ảnh gốc, thông tin chụp và liên kết với hồ sơ công trường.</p></div>{canUpload && <button className="ops-btn ops-create" onClick={() => setModal({ kind:"upload" })}>＋ Tải ảnh hiện trường</button>}</div>
    <div className="ops-toolbar"><label>Ngày tải<input type="date" value={filters.day} onChange={(event) => { setFilters({ ...filters,day:event.target.value }); setPage(1); }} /></label><label>Hạng mục<select value={filters.item} onChange={(event) => { setFilters({ ...filters,item:event.target.value }); setPage(1); }}><option value="">Tất cả</option>{lookup.data?.items.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>Người tải<select value={filters.uploader} onChange={(event) => { setFilters({ ...filters,uploader:event.target.value }); setPage(1); }}><option value="">Tất cả</option>{uploaders.map(([id,name]) => <option value={id} key={id}>{name}</option>)}</select></label><label>Đánh dấu<select value={filters.suspicious} onChange={(event) => { setFilters({ ...filters,suspicious:event.target.value }); setPage(1); }}><option value="">Tất cả</option><option value="yes">Nghi vấn</option><option value="no">Không đánh dấu</option></select></label><button className="ops-btn" onClick={state.reload}>Tải lại</button></div>
    {filtered.length ? <div className="ops-photo-grid">{filtered.slice((currentPage-1)*24,currentPage*24).map((photo) => <article className="ops-photo-card" key={photo.id}><button onClick={() => setModal({ kind:"photo",photo })} aria-label={`Xem ảnh ${photo.filename}`}><img src={photoUrl(projectId,photo.id)} alt={photo.filename} loading="lazy" /></button><div><h3>{photo.item_name}</h3><p>{photo.uploader} · {new Date(photo.created_at).toLocaleString("vi-VN")}</p>{photo.suspicious ? <span className="ops-badge ops-badge-orange">Nghi vấn · ngoài bán kính</span> : !photo.metadata.has_exif ? <span className="ops-badge ops-badge-gray">Không có metadata</span> : <span className="ops-badge ops-badge-green">Có metadata EXIF</span>}<p>{photo.journal_ids.length ? `Nhật ký #${photo.journal_ids.join(", #")}` : ""}{photo.acceptance_ids.length ? ` · Nghiệm thu #${photo.acceptance_ids.join(", #")}` : ""}</p></div></article>)}</div> : <Empty>Chưa có ảnh phù hợp với bộ lọc.</Empty>}
    {pages>1 && <div className="ops-pagination"><button className="ops-btn ops-small" disabled={currentPage === 1} onClick={() => setPage(currentPage-1)}>Trước</button><span>{currentPage} / {pages}</span><button className="ops-btn ops-small" disabled={currentPage === pages} onClick={() => setPage(currentPage+1)}>Sau</button></div>}
  </section></RemoteState>
    {modal?.kind === "upload" && <RecordEditor title="Tải ảnh hiện trường" initial={{ work_item_id:"",files:[] }} fields={[{ name:"work_item_id",label:"Hạng mục",type:"select",options:(lookup.data?.items || []).map((item) => ({ value:item.id,label:item.title })) }]} onClose={() => setModal(null)} onSaved={() => { setModal(null); setMessage("Đã tải ảnh lên công trường."); state.reload(); }} submit={async (values) => { if (!values.files.length) throw new Error("Chọn ít nhất một ảnh."); for (const entry of values.files) await uploadPhoto(projectId,values.work_item_id,entry.file,entry.uuid); }}>
      {(values,change) => <><label className="ops-field"><span>Ảnh JPEG / PNG / WebP, tối đa 10 MB/ảnh</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple required onChange={(event) => change("files",Array.from(event.target.files).map((file) => ({ file,uuid:crypto.randomUUID() })))} /></label><p className="ops-muted">{values.files.length} ảnh được chọn. Ảnh ngoài bán kính được đánh dấu để kiểm tra; ảnh thiếu EXIF vẫn được lưu.</p></>}
    </RecordEditor>}
    {modal?.kind === "photo" && <Modal className="photo-lightbox" title={modal.photo.filename} onClose={() => setModal(null)}><div className="photo-lightbox-layout"><div className="photo-lightbox-image"><img className="ops-photo-preview" src={photoUrl(projectId,modal.photo.id)} alt={modal.photo.filename} /></div><div className="photo-lightbox-meta"><dl className="ops-details-list"><dt>Hạng mục</dt><dd>{modal.photo.item_name}</dd><dt>Người tải</dt><dd>{modal.photo.uploader}</dd><dt>Thời điểm tải</dt><dd>{new Date(modal.photo.created_at).toLocaleString("vi-VN")}</dd><dt>Thời điểm chụp</dt><dd>{modal.photo.taken_at ? `${new Date(modal.photo.taken_at).toLocaleString("vi-VN")} (EXIF máy ảnh)` : "Không có metadata thời gian"}</dd><dt>Tọa độ</dt><dd>{modal.photo.latitude == null ? "Không có metadata GPS" : `${modal.photo.latitude}, ${modal.photo.longitude}`}</dd><dt>Khoảng cách tâm</dt><dd>{modal.photo.distance_m == null ? "Chưa có đủ tọa độ / cấu hình tâm" : `${Math.round(modal.photo.distance_m)} m`}</dd><dt>Thiết bị</dt><dd>{[modal.photo.metadata.make,modal.photo.metadata.model].filter(Boolean).join(" ") || "Không có metadata"}</dd></dl>{modal.photo.suspicious && <Notice tone="warning">Ảnh được ghi nhận ngoài bán kính công trường. Đây là dấu hiệu cần kiểm tra, không phải kết luận ảnh giả.</Notice>}<a className="ops-btn ops-primary" href={photoUrl(projectId,modal.photo.id,true)} target="_blank" rel="noreferrer">Mở ảnh gốc</a></div></div></Modal>}
  </>;
}
export default function SitePhotos() { const [params] = useSearchParams(); const projectId = params.get("projectId"); return <DashboardLayout title="Ảnh hiện trường" description="Hình ảnh thi công, metadata và hồ sơ liên quan trong cùng một thư viện.">{validProjectId(projectId) ? <ProjectPhotos key={projectId} projectId={projectId} /> : <NoProject />}</DashboardLayout>; }
